#!/usr/bin/env bash

set -eu -o pipefail

if ! command -v node >/dev/null 2>&1; then
    if [[ "$OSTYPE" == "darwin"* ]]; then
        echo "Please install NodeJS from https://nodejs.org/en/download"
        exit 0
    fi
    echo "Cannot find Node"
    read -p "Would you like to install Node (Warning: this will modify PATH and .bashrc)? (y/n): " -n 1 confirmation
    echo ""
    if [[ "$confirmation" =~ ^[Yy]$ ]]; then
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
        ~/.nvm/nvm.sh install node
        ~/.nvm/nvm.sh use node
    else
        exit 1
    fi
fi

npm install
npx tsc -b
