#!/usr/bin/env bash

set -eu -o pipefail
pushd "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)" > /dev/null

if ! [ -d "apgmera" ]; then
    git clone https://gitlab.com/apgoucher/apgmera
fi
node ./lib/misc/rss.js "$@"

popd > /dev/null
