#!/usr/bin/env bash

set -eu -o pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
pushd "$SCRIPT_DIR" > /dev/null

if ! [ -d "apgmera" ]; then
    git clone https://gitlab.com/apgoucher/apgmera
fi
node ./lib/misc/rss.js "$@"

popd > /dev/null
