#!/usr/bin/env bash

set -eu -o pipefail

if ! [ -d "apgmera" ]; then
    git clone https://gitlab.com/apgoucher/apgmera
fi

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
node "$SCRIPT_DIR/lib/misc/rss.js" "$@"
