#!/usr/bin/env bash

set -eu -o pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
pushd "$SCRIPT_DIR" > /dev/null

git stash push -- src/version.ts
git pull
npm install
npx tsc -b
./build

popd > /dev/null
