
/** Finds the minimum and maximum rule of patterns. */

import {LifewebError} from './util.js';
import {Pattern, IdentityPattern} from './pattern.js';
import {INTSpec, INT, INT_SPECS, arrayToTransitions, unparseTransitions, unparseMAP, MAPPattern, MAPB0Pattern, MAPGenPattern} from './map.js';
import {unparseHROTRanges, HROTPattern, HROTB0Pattern} from './hrot.js';
import {AlternatingPattern} from './alternating.js';
import {FinitePattern, TorusPattern} from './bounded.js';
import {TreePattern} from './ruleloader.js';


export class MinmaxError extends LifewebError {
    name: 'MinmaxError' = 'MinmaxError';
    [Symbol.toStringTag]: 'MinmaxError' = 'MinmaxError';
}


/** Stores information about the phases of a pattern. */
export interface PhaseData<T extends Pattern = Pattern> {
    /** The populations of each generation. */
    pops: number[];
    /** The 32-bit hash generated by `hash32` for each phase. */
    hashes: number[];
    /** Data for each generation. */
    phases: T[];
}


/** Verifies that a pattern is consistent with a given `PhaseData`. */
function verifyType(p: Pattern, data: PhaseData, gens: number, step: number): boolean {
    p = p.copy();
    let counter = 0;
    for (let i = 0; i <= gens; i += step) {
        if (p.hash32() !== data.hashes[counter] || p.population !== data.pops[counter]) {
            return false;
        }
        if (!p.isEqual(data.phases[counter])) {
            return false;
        }
        p.run(step);
        p.shrinkToFit();
        counter++;
    }
    return true;
}

/** Finds minimum and maximum rules for patterns in non-B0 isotropic rules
 * @param allTrs Generally either `TRANSITIONS` or `HEX_TRANSITIONS`.
 */
function isotropicMinmax(p: MAPPattern | MAPGenPattern, data: PhaseData, gens: number, step: number, spec: INTSpec): false | {minB: string[], minS: string[], maxB: string[], maxS: string[]} {
    let value = arrayToTransitions(p.trs, spec);
    if (!value) {
        return false;
    }
    let [b, s] = value;
    let minB = new Set(b);
    let minS = new Set(s);
    let maxB = new Set(b);
    let maxS = new Set(s);
    for (let tr in spec.trs) {
        let q = p.copy();
        q.trs = q.trs.slice();
        if (tr !== '0c') {
            if (minB.has(tr)) {
                for (let i of spec.trs[tr]) {
                    q.trs[i] = 0;
                }
                if (verifyType(q, data, gens, step)) {
                    minB.delete(tr);
                }
            } else {
                for (let i of spec.trs[tr]) {
                    q.trs[i] = 1;
                }
                if (verifyType(q, data, gens, step)) {
                    maxB.add(tr);
                }
            }
            q = p.copy();
            q.trs = q.trs.slice();
        }
        if (minS.has(tr)) {
            for (let i of spec.trs[tr]) {
                q.trs[i | (1 << 4)] = 0;
            }
            if (verifyType(q, data, gens, step)) {
                minS.delete(tr);
            }
        } else {
            for (let i of spec.trs[tr]) {
                q.trs[i | (1 << 4)] = 1;
            }
            if (verifyType(q, data, gens, step)) {
                maxS.add(tr);
            }
        }
    }
    return {
        minB: Array.from(minB),
        minS: Array.from(minS),
        maxB: Array.from(maxB),
        maxS: Array.from(maxS),
    };
}

/** Finds minimum and maximum rules for patterns in B0 isotropic rules
 * @param allTrs Generally either `TRANSITIONS` or `HEX_TRANSITIONS`.
 */
function isotropicB0Minmax(p: MAPB0Pattern, data: PhaseData, gens: number, step: number, spec: INTSpec): false | {minB: string[], minS: string[], maxB: string[], maxS: string[]} {
    let value = arrayToTransitions(p.evenTrs.map(x => 1 - x), spec);
    if (!value) {
        return false;
    }
    let [b, s] = value;
    b.push('0c');
    let minB = new Set(b);
    let minS = new Set(s);
    let maxB = new Set(b);
    let maxS = new Set(s);
    for (let tr in spec.trs) {
        if (tr !== '0c') {
            let q = p.copy();
            q.evenTrs = q.evenTrs.slice();
            q.oddTrs = q.oddTrs.slice();
            if (minB.has(tr)) {
                for (let i of spec.trs[tr]) {
                    q.evenTrs[i] = 1;
                    q.oddTrs[511 - i] = 0;
                }
                if (verifyType(q, data, gens, step)) {
                    minB.delete(tr);
                }
            } else {
                for (let i of spec.trs[tr]) {
                    q.evenTrs[i] = 0;
                    q.oddTrs[511 - i] = 1;
                }
                if (verifyType(q, data, gens, step)) {
                    maxB.add(tr);
                }
            }
        }
        if (tr !== '8c') {
            let q = p.copy();
            q.evenTrs = q.evenTrs.slice();
            q.oddTrs = q.oddTrs.slice();
            if (minS.has(tr)) {
                for (let i of spec.trs[tr]) {
                    q.evenTrs[i | (1 << 4)] = 1;
                    q.oddTrs[511 - (i | (1 << 4))] = 0;
                }
                if (verifyType(q, data, gens, step)) {
                    minS.delete(tr);
                }
            } else {
                for (let i of spec.trs[tr]) {
                    q.evenTrs[i | (1 << 4)] = 0;
                    q.oddTrs[511 - (i | (1 << 4))] = 1;
                }
                if (verifyType(q, data, gens, step)) {
                    maxS.add(tr);
                }
            }
        }
    }
    return {
        minB: Array.from(minB),
        minS: Array.from(minS),
        maxB: Array.from(maxB),
        maxS: Array.from(maxS),
    };
}

/** Finds minimum and maximum rules for MAP string rules (https://conwaylife.com/wiki/Non-isotropic_rule). */
function mapStringMinmax(p: MAPPattern | MAPGenPattern, data: PhaseData, gens: number, step: number): [string, string] {
    let min = p.trs.slice();
    let max = p.trs.slice();
    for (let i = 0; i < 512; i++) {
        let q = p.copy();
        q.trs[i] = 1 - q.trs[i];
        if (verifyType(q, data, gens, step)) {
            if (q.trs[i]) {
                min[i] = 0;
            } else {
                max[i] = 1;
            }
        }
        q.trs[i] = 1 - q.trs[i];
    }
    return [unparseMAP(min, p.rule.states), unparseMAP(max, p.rule.states)];
}

/** Finds minimum and maximum rules for MAP string rules (https://conwaylife.com/wiki/Non-isotropic_rule) with B0. */
function mapB0StringMinmax(p: MAPB0Pattern, data: PhaseData, gens: number, step: number): [string, string] {
    let min = p.evenTrs.map(x => 1 - x);
    let max = p.evenTrs.map(x => 1 - x);
    for (let i = 0; i < 512; i++) {
        let q = p.copy();
        q.evenTrs[i] = 1 - q.evenTrs[i];
        q.oddTrs[511 - i] = 1 - q.oddTrs[511 - i];
        if (verifyType(q, data, gens, step)) {
            if (q.evenTrs[i]) {
                min[i] = 1;
            } else {
                max[i] = 0;
            }
        }
        q.evenTrs[i] = 1 - q.evenTrs[i];
        q.oddTrs[511 - i] = 1 - q.oddTrs[511 - i];
    }
    return [unparseMAP(min, p.rule.states), unparseMAP(max, p.rule.states)];
}

/** Finds minimum and maximum rules for patterns in the 2**512 2-state range-1 Moore-neighborhood rules. */
function mapMinmax(p: MAPPattern | MAPB0Pattern | MAPGenPattern, data: PhaseData, gens: number, step: number): [string, string] {
    p.shrinkToFit();
    if (p.rule.str.startsWith('MAP')) {
        let min: string, max: string;
        if (p instanceof MAPPattern || p instanceof MAPGenPattern) {
            [min, max] = mapStringMinmax(p, data, gens, step);
        } else {
            [min, max] = mapB0StringMinmax(p, data, gens, step);
        }
        if (p instanceof MAPGenPattern) {
            min += '/' + p.rule.states;
            max += '/' + p.rule.states;
        }
        return [min, max];
    }
    let nhLetter: keyof typeof INT_SPECS;
    let spec: INTSpec;
    let last = p.rule.str[p.rule.str.length - 1];
    if (last in INT_SPECS) {
        nhLetter = last as typeof nhLetter;
        spec = INT_SPECS[nhLetter];
    } else {
        nhLetter = 'M';
        spec = INT;
    }
    let out: ReturnType<typeof isotropicMinmax>;
    if (p instanceof MAPPattern || p instanceof MAPGenPattern) {
        out = isotropicMinmax(p, data, gens, step, spec);
    } else {
        out = isotropicB0Minmax(p, data, gens, step, spec);
    }
    if (!out) {
        let min: string, max: string;
        if (p instanceof MAPPattern || p instanceof MAPGenPattern) {
            [min, max] = mapStringMinmax(p, data, gens, step);
        } else {
            [min, max] = mapB0StringMinmax(p, data, gens, step);
        }
        if (p instanceof MAPGenPattern) {
            min += '/' + p.rule.states;
            max += '/' + p.rule.states;
        }
        return [min, max];
    }
    let minB = unparseTransitions(out.minB, spec);
    let minS = unparseTransitions(out.minS, spec);
    let maxB = unparseTransitions(out.maxB, spec);
    let maxS = unparseTransitions(out.maxS, spec);
    let min: string;
    let max: string;
    if (p instanceof MAPPattern || p instanceof MAPB0Pattern) {
        min = `B${minB}/S${minS}`;
        max = `B${maxB}/S${maxS}`;
    } else {
        min = `${minS}/${minB}/${p.rule.states}`;
        max = `${maxS}/${maxB}/${p.rule.states}`;
    }
    if (nhLetter !== 'M') {
        min += nhLetter;
        max += nhLetter;
    }
    return [min, max];
}

/** Finds minimum and maximum rules for patterns in OT non-B0 rules. */
function otMinmax(p: MAPPattern | MAPGenPattern, minB: number[], minS: number[], data: PhaseData, gens: number, step: number, spec: INTSpec): [number[], number[], number[], number[]] {
    let maxB = minB.slice();
    let maxS = minS.slice();
    for (let i = 0; i < spec.validTrs.length; i++) {
        let q = p.copy();
        q.trs = q.trs.slice();
        if (i !== 0) {
            if (minB.includes(i)) {
                for (let letter of spec.validTrs[i]) {
                    for (let tr of spec.trs[i + letter]) {
                        q.trs[tr] = 0;
                    }
                }
                if (verifyType(q, data, gens, step)) {
                    minB.splice(minB.indexOf(i), 1);
                }
            } else {
                for (let letter of spec.validTrs[i]) {
                    for (let tr of spec.trs[i + letter]) {
                        q.trs[tr] = 1;
                    }
                }
                if (verifyType(q, data, gens, step)) {
                    maxB.push(i);
                }
            }
            q = p.copy();
            q.trs = q.trs.slice();
        }
        if (minS.includes(i)) {
            for (let letter of spec.validTrs[i]) {
                for (let tr of spec.trs[i + letter]) {
                    q.trs[tr | (1 << 4)] = 0;
                }
            }
            if (verifyType(q, data, gens, step)) {
                minS.splice(minS.indexOf(i), 1);
            }
        } else {
            for (let letter of spec.validTrs[i]) {
                for (let tr of spec.trs[i + letter]) {
                    q.trs[tr | (1 << 4)] = 1;
                }
            }
            if (verifyType(q, data, gens, step)) {
                maxS.push(i);
            }
        }
    }
    return [minB, minS, maxB, maxS];
}

/** Finds minimum and maximum rules for patterns in OT B0 rules. */
function otB0Minmax(p: MAPB0Pattern, minB: number[], minS: number[], data: PhaseData, gens: number, step: number, spec: INTSpec): [number[], number[], number[], number[]] {
    let maxB = minB.slice();
    let maxS = minS.slice();
    for (let i = 0; i < spec.validTrs.length; i++) {
        if (i !== 0) {
            let q = p.copy();
            q.evenTrs = q.evenTrs.slice();
            q.oddTrs = q.oddTrs.slice();
            if (minB.includes(i)) {
                for (let letter of spec.validTrs[i]) {
                    for (let tr of spec.trs[i + letter]) {
                        q.evenTrs[tr] = 1;
                        q.oddTrs[511 - tr] = 0;
                    }
                }
                if (verifyType(q, data, gens, step)) {
                    minB.splice(minB.indexOf(i), 1);
                }
            } else {
                for (let letter of spec.validTrs[i]) {
                    for (let tr of spec.trs[i + letter]) {
                        q.evenTrs[tr] = 0;
                        q.oddTrs[511 - tr] = 1;
                    }
                }
                if (verifyType(q, data, gens, step)) {
                    maxB.push(i);
                }
            }
        }
        if (i !== 8) {
            let q = p.copy();
            q.evenTrs = q.evenTrs.slice();
            q.oddTrs = q.oddTrs.slice();
            if (minS.includes(i)) {
                for (let letter of spec.validTrs[i]) {
                    for (let tr of spec.trs[i + letter]) {
                        q.evenTrs[tr | (1 << 4)] = 1;
                        q.oddTrs[511 - (tr | (1 << 4))] = 0;
                    }
                }
                if (verifyType(q, data, gens, step)) {
                    minS.splice(minS.indexOf(i), 1);
                }
            } else {
                for (let letter of spec.validTrs[i]) {
                    for (let tr of spec.trs[i + letter]) {
                        q.evenTrs[tr | (1 << 4)] = 0;
                        q.oddTrs[511 - (tr | (1 << 4))] = 1;
                    }
                }
                if (verifyType(q, data, gens, step)) {
                    maxS.push(i);
                }
            }
        }
    }
    return [minB, minS, maxB, maxS];
}

/** Finds minimum and maximum rules for patterns in OT rules. */
function fullOTMinmax(p: MAPPattern | MAPB0Pattern | MAPGenPattern, data: PhaseData, gens: number, step: number): [string, string] {
    let nhLetter: keyof typeof INT_SPECS;
    let spec: INTSpec;
    let last = p.rule.str[p.rule.str.length - 1];
    if (last in INT_SPECS) {
        nhLetter = last as typeof nhLetter;
        spec = INT_SPECS[nhLetter];
    } else {
        nhLetter = 'M';
        spec = INT;
    }
    let startB: number[] = [];
    let startS: number[] = [];
    let trs = 'trs' in p ? p.trs : p.evenTrs.map(x => 1 - x);
    for (let i = 0; i < spec.validTrs.length; i++) {
        let bFound = false;
        let sFound = false;
        for (let letter of spec.validTrs[i]) {
            if (trs[spec.trs[i + letter][0]]) {
                bFound = true;
            }
            if (trs[spec.trs[i + letter][0] | (1 << 4)]) {
                sFound = true;
            }
        }
        if (bFound) {
            startB.push(i);
        }
        if (sFound) {
            startS.push(i);
        }
    }
    let outData: number[][] = [];
    if (p instanceof MAPPattern || p instanceof MAPGenPattern) {
        outData = otMinmax(p, startB, startS, data, gens, step, spec);
    } else {
        outData = otB0Minmax(p, startB, startS, data, gens, step, spec);
    }
    let [minB, minS, maxB, maxS] = outData.map(x => x.sort((x, y) => x - y).join(''));
    if (p instanceof MAPPattern || p instanceof MAPB0Pattern) {
        return [`B${minB}/S${minS}`, `B${maxB}/S${maxS}`];
    } else {
        return [`${minS}/${minB}/${p.rule.states}`, `${maxS}/${maxB}/${p.rule.states}`];
    }
}

/** Finds minimum and maximum rules for patterns in HROT rules without B0. */
function hrotMinmax(p: HROTPattern, data: PhaseData, gens: number, step: number): [string, string] {
    let parts = p.rule.str.split(',');
    let min = `${parts[0]},${parts[1]},S`;
    let max = `${parts[0]},${parts[1]},S`;
    let minS = p.s.slice();
    let maxS = p.s.slice();
    for (let i = 0; i < minS.length; i++) {
        if (minS[i]) {
            p.s[i] = 0;
            if (verifyType(p, data, gens, step)) {
                minS[i] = 0;
            }
            p.s[i] = 1;
        } else {
            p.s[i] = 1;
            if (verifyType(p, data, gens, step)) {
                maxS[i] = 1;
            }
            p.s[i] = 0;
        }
    }
    min += unparseHROTRanges(minS) + ',B';
    max += unparseHROTRanges(maxS) + ',B';
    let minB = p.b.slice();
    let maxB = p.b.slice();
    for (let i = 1; i < minB.length; i++) {
        if (minB[i]) {
            p.b[i] = 0;
            if (verifyType(p, data, gens, step)) {
                minB[i] = 0;
            }
            p.b[i] = 1;
        } else {
            p.b[i] = 1;
            if (verifyType(p, data, gens, step)) {
                maxB[i] = 1;
            }
            p.b[i] = 0;
        }
    }
    min += unparseHROTRanges(minB);
    max += unparseHROTRanges(maxB);
    let last = parts[parts.length - 1];
    if (last.startsWith('N')) {
        min += ',' + last;
        max += ',' + last;
    }
    return [min, max];
}

/** Finds minimum and maximum rules for patterns in HROT rules with B0. */
function hrotB0Minmax(p: HROTB0Pattern, data: PhaseData, gens: number, step: number): [string, string] {
    let parts = p.rule.str.split(',');
    let min = `${parts[0]},${parts[1]},S`;
    let max = `${parts[0]},${parts[1]},S`;
    let minS = p.evenS.map(x => 1 - x);
    let maxS = p.evenS.map(x => 1 - x);
    for (let i = 0; i < minS.length; i++) {
        if (minS[i]) {
            p.evenS[i] = 1;
            p.oddS[minS.length - 1 - i] = 0;
            if (verifyType(p, data, gens, step)) {
                minS[i] = 0;
            }
            p.evenS[i] = 0;
            p.oddS[minS.length - 1 - i] = 1;
        } else {
            p.evenS[i] = 0;
            p.oddS[minS.length - 1 - i] = 1;
            if (verifyType(p, data, gens, step)) {
                maxS[i] = 1;
            }
            p.evenS[i] = 1;
            p.oddS[minS.length - 1 - i] = 0;
        }
    }
    min += unparseHROTRanges(minS) + ',B';
    max += unparseHROTRanges(maxS) + ',B';
    let minB = p.evenB.map(x => 1 - x);
    let maxB = p.evenB.map(x => 1 - x);
    for (let i = 0; i < minB.length; i++) {
        if (minB[i]) {
            p.evenB[i] = 1;
            p.oddB[minB.length - 1 - i] = 0;
            if (verifyType(p, data, gens, step)) {
                minB[i] = 0;
            }
            p.evenB[i] = 0;
            p.oddB[minB.length - 1 - i] = 1;
        } else {
            p.evenB[i] = 0;
            p.oddB[minB.length - 1 - i] = 1;
            if (verifyType(p, data, gens, step)) {
                maxB[i] = 1;
            }
            p.evenB[i] = 1;
            p.oddB[minB.length - 1 - i] = 0;
        }
    }
    min += unparseHROTRanges(minB);
    max += unparseHROTRanges(maxB);
    if (parts.length === 5) {
        min += ',' + parts[4];
        max += ',' + parts[4];
    }
    return [min, max];
}

/** Finds minimum and maximum rules for patterns in alternating-time rules. */
function alternatingMinmax(p: AlternatingPattern, data: PhaseData, gens: number, step: number, ot?: boolean): [string, string] {
    let min: string[] = [];
    let max: string[] = [];
    let count = p.patterns.length * step;
    for (let i = 0; i < count; i += step) {
        let q = p.patterns[i % p.patterns.length].copy();
        let phase = data.phases[i];
        q.setData(phase.height, phase.width, phase.getData());
        q.xOffset = phase.xOffset;
        q.yOffset = phase.yOffset;
        let newData: PhaseData = {pops: [], hashes: [], phases: []};
        for (let j = i; j <= gens; j += count) {
            newData.pops.push(data.pops[j]);
            newData.hashes.push(data.hashes[j]);
            newData.phases.push(data.phases[j]);
        }
        let newGens = Math.ceil((gens - i) / count) + 1;
        let minmax = findMinmax(q, newGens, newData, count, ot);
        min.push(minmax[0]);
        max.push(minmax[1]);
    }
    return [min.join('|'), max.join('|')];
}

/** Finds minimum and maximum rules for patterns for a given number of generations.
 * @param data An optional `PhaseData` to take place of the auto-generated one.
 * @param step The step used while running patterns, used internally.
 * @param ot Whether to use outer-totalistic minmax instead of isotropic minmax when available.
*/
export function findMinmax<T extends Pattern>(p: T, gens: number, data?: PhaseData<T>, step: number = 1, ot?: boolean): [string, string] {
    p = p.copy().shrinkToFit();
    if (data === undefined) {
        let pops: number[] = [p.population];
        let hashes: number[] = [p.hash32()];
        let phases: T[] = [p.copy()];
        let q = p.copy();
        for (let i = 0; i < gens + 1; i++) {
            q.run(step);
            q.shrinkToFit();
            pops.push(q.population);
            hashes.push(q.hash32());
            phases.push(q.copy());
        }
        data = {pops, hashes, phases};
    } else {
        let q = data.phases[data.phases.length - 1].copy();
        q.run(step);
        q.shrinkToFit();
        data.pops.push(q.population);
        data.hashes.push(q.hash32());
        data.phases.push(q);
    }
    if (p instanceof MAPPattern || p instanceof MAPGenPattern || p instanceof MAPB0Pattern) {
        if (ot && p.rule.symmetry === 'D8') {
            return fullOTMinmax(p, data, gens, step);
        } else {
            return mapMinmax(p, data, gens, step);
        }
    } else if (p instanceof HROTPattern) {
        return hrotMinmax(p, data, gens, step);
    } else if (p instanceof HROTB0Pattern) {
        return hrotB0Minmax(p, data, gens, step);
    } else if (p instanceof AlternatingPattern) {
        return alternatingMinmax(p, data, gens, step, ot);
    } else if (p instanceof TreePattern) {
        return [p.rule.str, p.rule.str];
    } else if (p instanceof IdentityPattern) {
        return ['Identity', 'Identity'];
    } else if (p instanceof FinitePattern || p instanceof TorusPattern) {
        let q = p.pattern;
        q.setData(p.height, p.width, p.data);
        return findMinmax(q, gens, undefined, step, ot).map(rule => {
            return `${rule}:${p instanceof FinitePattern ? 'P' : 'T'}${p.width},${p.height}`;
        }) as [string, string];
    } else {
        throw new MinmaxError(`Unknown pattern: ${p.constructor.name}`);
    }
}
